# Generated by Django 4.2.1 on 2023-07-15 19:16

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Назва медіа даних')),
                ('files', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True), size=None), editable=False, size=None, verbose_name='Телеграм ID файлів')),
                ('content_type', models.CharField(choices=[('VIDEO', 'Відео'), ('PHOTO', 'Фото')], editable=False, verbose_name='Тип файлів')),
            ],
            options={
                'verbose_name': 'медіа',
                'verbose_name_plural': 'медіа',
                'db_table': 'medias',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Назва закладу')),
                ('category', models.CharField(max_length=20, verbose_name='Категорія')),
                ('address', models.CharField(max_length=500, verbose_name='Адреса')),
                ('cashback', models.CharField(max_length=50, null=True, verbose_name='Кешбек')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Телефон')),
                ('city', models.CharField(default='Київ', max_length=20, verbose_name='Місто')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Додаткова інформація')),
                ('priority', models.IntegerField(blank=True, null=True, verbose_name='Приоритетність')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='femfatale.media', verbose_name='Медіа пакунок')),
            ],
            options={
                'verbose_name': 'партнер',
                'verbose_name_plural': 'партнери',
                'db_table': 'partners',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Телеграм ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('status', models.CharField(choices=[('ACTIVE', 'Активний'), ('INACTIVE', 'Не активний'), ('UNAUTHORIZED', 'Не авторизований')], default='UNAUTHORIZED', verbose_name='Статус')),
                ('role', models.CharField(choices=[('ADMIN', 'Адмін'), ('USER', 'Клієнт'), ('MODERATOR', 'Модератор'), ('COMPETITION', 'Конкурент'), ('PARTNER', 'Партнер')], default='USER', verbose_name='Роль')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Телефон')),
                ('card', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Карта клієнта')),
                ('bankcard', models.CharField(blank=True, max_length=16, null=True, verbose_name='Банківська карта')),
                ('balance', models.BigIntegerField(default=0, help_text='*Рахується автоматично', verbose_name='Баланс, грн')),
                ('info', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Коментар для адміністраторів')),
            ],
            options={
                'verbose_name': 'клієнт',
                'verbose_name_plural': 'клієнти',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payout_date', models.DateTimeField(default=datetime.datetime(2023, 7, 15, 22, 16, 58, 878282), verbose_name='Дата чеку')),
                ('price', models.IntegerField(help_text="Обов'язкове поле", verbose_name='Чиста сума чеку, грн')),
                ('general_price', models.IntegerField(blank=True, help_text='*Рахується автоматично після зберігання', null=True, verbose_name='Загальний кешбек, грн')),
                ('service_price', models.IntegerField(blank=True, help_text='*Рахується автоматично після зберігання', null=True, verbose_name='Наш кешбек, грн')),
                ('user_price', models.IntegerField(blank=True, help_text='*Рахується автоматично після зберігання', null=True, verbose_name='Кешбек клієнта, грн')),
                ('general_percent', models.IntegerField(help_text="Загальний відсоток кешбеку, який нам платить заклад. Обов'язкове поле", verbose_name='Загальний кешбек')),
                ('service_percent', models.IntegerField(help_text="Відсоток кешбеку, який ми залишаємо собі. Обов'язкове поле", verbose_name='Наш прибуток')),
                ('user_percent', models.IntegerField(help_text="Відсоток кешбеку, який отримає клієнт. Обов'язкове поле", verbose_name='Кешбкек клієнта')),
                ('comment', models.CharField(blank=True, help_text='Цей коментар побачить клієнт', max_length=1000, null=True, verbose_name='Коментар для клієнта')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Коментар для адміністраторів')),
                ('type', models.CharField(choices=[('MINUS', 'Списання'), ('PLUS', 'Нарахування')], default='MINUS', verbose_name='Тип операції')),
                ('tag', models.CharField(choices=[('default', 'Початковий баланс'), ('edited', 'Створений адміном платіж')], default='edited', verbose_name='Тип платежу')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='femfatale.media', verbose_name='Фото чеку')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='femfatale.partner', verbose_name='Заклад')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='femfatale.user', verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'платіж',
                'verbose_name_plural': 'платежі',
                'db_table': 'payouts',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=1060, verbose_name='Основний текст')),
                ('status', models.CharField(choices=[('ACTIVE', 'Опублікована'), ('HIDE', 'Прихована')], default='HIDE', verbose_name='Статус')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='femfatale.media', verbose_name='Медіа файли')),
            ],
            options={
                'verbose_name': 'новина',
                'verbose_name_plural': 'новини',
                'db_table': 'articles',
            },
        ),
    ]
