# Generated by Django 4.2.1 on 2023-06-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femfatale', '0003_alter_partner_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Телеграм ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('status', models.CharField(choices=[('ACTIVE', 'Активний'), ('INACTIVE', 'Не активний'), ('UNAUTHORIZED', 'Не авторизований')], default='UNAUTHORIZED', verbose_name='Статус')),
                ('role', models.CharField(choices=[('ADMIN', 'Адмін'), ('USER', 'Клієнт'), ('MODERATOR', 'Модератор'), ('COMPETITION', 'Конкурент'), ('PARTNER', 'Партнер')], default='USER', verbose_name='Роль')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Телефон')),
                ('card', models.CharField(blank=True, max_length=10, null=True, verbose_name='Карточка')),
                ('bankcard', models.CharField(blank=True, max_length=16, null=True, verbose_name='Банківська карта')),
                ('balance', models.BigIntegerField(default=0, verbose_name='Баланс')),
                ('info', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Додаткова інформація')),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Партнери',
                'db_table': 'users',
            },
        ),
        migrations.AlterField(
            model_name='partner',
            name='city',
            field=models.CharField(default='Київ', max_length=20, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Додаткова інформація'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Телефон'),
        ),
    ]
